#!/bin/sh
EDIR=.
# les jars associes
GJAR=${EDIR}/eggc-5.3.1.jar:.

#--------------------------------------------------------
# java, javac, jar
#JDIR=/usr/local/jdk1.6/bin
JDIR=/usr/bin

${JDIR}/java -classpath ${GJAR} mcs.compiler.MCSC $*
